import { createClient } from '@supabase/supabase-js'

export default defineEventHandler(async (event) => {
  try {
    const config = useRuntimeConfig()
    const supabase = createClient(
      config.supabaseUrl!,
      config.supabaseServiceKey!
    )

    const body = await readBody(event)

    const {
      supplier_id,
      expected_delivery_date,
      tax_amount = 0,
      shipping_cost = 0,
      notes,
      items,
      subtotal,
      total_amount,
      created_by
    } = body || {}

    if (!supplier_id || !Array.isArray(items) || items.length === 0) {
      throw createError({
        statusCode: 400,
        statusMessage: 'supplier_id and at least one item are required'
      })
    }

    if (typeof subtotal !== 'number' || typeof total_amount !== 'number') {
      throw createError({
        statusCode: 400,
        statusMessage: 'subtotal and total_amount must be numeric'
      })
    }

    if (!created_by) {
      throw createError({
        statusCode: 400,
        statusMessage: 'created_by is required'
      })
    }

    // Validate items shape
    const invalidItem = items.find((item: any) =>
      !item.inventory_item_id ||
      typeof item.quantity_ordered !== 'number' ||
      typeof item.unit_price !== 'number'
    )

    if (invalidItem) {
      throw createError({
        statusCode: 400,
        statusMessage: 'Each item must have inventory_item_id, numeric quantity_ordered and unit_price'
      })
    }

    // Insert purchase order (po_number generated by DB trigger). Always start in 'draft' status.
    const { data: purchaseOrder, error: poError } = await supabase
      .from('purchase_orders')
      .insert({
        supplier_id,
        expected_delivery_date: expected_delivery_date || null,
        status: 'draft',
        subtotal,
        tax_amount,
        shipping_cost,
        total_amount,
        notes: notes || null,
        created_by
      })
      .select('*')
      .single()

    if (poError || !purchaseOrder) {
      throw createError({
        statusCode: 400,
        statusMessage: poError?.message || 'Failed to create purchase order'
      })
    }

    // Insert purchase order items
    const itemsPayload = (items as any[]).map((item) => ({
      purchase_order_id: purchaseOrder.id,
      inventory_item_id: item.inventory_item_id,
      quantity_ordered: item.quantity_ordered,
      quantity_received: 0,
      unit_price: item.unit_price,
      total_price: item.total_price ?? (item.quantity_ordered * item.unit_price),
      notes: item.notes || null
    }))

    const { error: itemsError } = await supabase
      .from('purchase_order_items')
      .insert(itemsPayload)

    if (itemsError) {
      throw createError({
        statusCode: 400,
        statusMessage: itemsError.message
      })
    }

    return {
      success: true,
      data: {
        ...purchaseOrder,
        items: itemsPayload
      }
    }
  } catch (error: any) {
    throw createError({
      statusCode: 500,
      statusMessage: error.message || 'Internal server error'
    })
  }
})
